INSERT INTO departamentos (id, provincia_id, nombre) VALUES (1, 1, 'AZUL');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (2, 1, 'PUAN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (3, 1, 'LA MATANZA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (4, 1, 'TIGRE');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (5, 1, '25 DE MAYO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (6, 1, 'TRENQUE LAUQUEN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (7, 1, '9 DE JULIO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (8, 1, 'LANUS');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (9, 1, 'LA PLATA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (10, 1, 'MONTE');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (11, 1, 'PEHUAJO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (12, 1, 'SAN ISIDRO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (13, 1, 'PERGAMINO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (14, 1, 'ALBERTI');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (15, 1, 'CHASCOMUS');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (16, 1, 'ESTEBAN ECHEVERRIA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (17, 1, 'MERCEDES');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (18, 1, 'BAHIA BLANCA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (19, 1, 'MERLO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (20, 1, 'JUNIN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (21, 1, 'GUAMINI');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (22, 1, 'LUJAN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (23, 1, 'LEANDRO N.ALEM');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (24, 1, 'MATANZA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (25, 1, 'GENERAL PAZ');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (26, 1, 'SAN VICENTE');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (27, 1, 'CAÑUELAS');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (28, 1, 'ALMIRANTE BROWN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (29, 1, 'CNL.DE MARINA  L.ROSALES');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (30, 1, 'BARADERO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (31, 1, 'SAAVEDRA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (32, 1, 'BRANDSEN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (33, 1, 'GENERAL SARMIENTO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (34, 1, 'TAPALQUE');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (35, 1, 'SALADILLO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (36, 1, 'MAGDALENA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (37, 1, 'GONZALES CHAVES');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (38, 1, 'GENERAL PINTO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (39, 1, 'NAVARRO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (40, 1, 'DAIREAUX');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (41, 1, 'LOBOS');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (42, 1, 'CORONEL DORREGO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (43, 1, 'ADOLFO ALSINA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (44, 1, 'COLON');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (45, 1, 'GENERAL ARENALES');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (46, 1, 'LINCOLN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (47, 1, 'VILLARINO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (48, 1, 'VICENTE LOPEZ');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (49, 1, 'BARTOLOME MITRE');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (50, 1, 'EXALTACION DE LA CRUZ');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (51, 1, 'SALTO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (52, 1, 'BRAGADO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (53, 1, 'ZARATE');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (54, 1, 'AVELLANEDA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (55, 1, 'AYACUCHO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (56, 1, 'SAN ANDRES DE GILES');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (57, 1, 'TANDIL');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (58, 1, 'RIVADAVIA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (59, 1, 'PATAGONES');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (60, 1, 'GRL.VIAMONTE');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (61, 1, 'CNL.DE MARINA LEONARDO ROSALES');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (62, 1, 'BALCARCE');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (63, 1, 'TRES ARROYOS');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (64, 1, 'GENERAL VILLEGAS');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (65, 1, 'LOMAS DE ZAMORA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (66, 1, 'BERISSO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (67, 1, 'JUAREZ');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (68, 1, 'GRL.PUEYRREDON');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (69, 1, 'CORONEL SUAREZ');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (70, 1, 'ESCOBAR');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (71, 1, 'CARLOS CASARES');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (72, 1, 'CHIVILCOY');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (73, 1, 'BERAZATEGUI');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (74, 1, 'QUILMES');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (75, 1, 'TORQUINST');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (76, 1, '3 DE FEBRERO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (77, 1, 'OLAVARRIA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (78, 1, 'PELLEGRINI');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (79, 1, 'GENERAL BELGANO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (80, 1, 'FLORENCIO VARELA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (81, 1, 'SALLIQUELO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (82, 1, 'CNL.DE MARINA L.ROSALES');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (83, 1, 'MAR CHIQUITA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (84, 1, 'GENERAL PUEYRREDON');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (85, 1, 'CAMPANA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (86, 1, 'GRL.SARMIENTO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (87, 1, 'ROJAS');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (88, 1, 'SARMIENTO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (89, 1, 'CARMEN DE ARECO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (90, 1, 'PILA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (91, 1, 'TRES DE FEBRERO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (92, 1, 'MORON');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (93, 1, 'CASTELLI');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (94, 1, 'CHACABUCO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (95, 1, 'GENERAL VIAMONTE');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (96, 1, 'RAUCH');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (97, 1, 'GENERAL BELGRANO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (98, 1, 'TORNQUIST');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (99, 1, 'NECOCHEA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (100, 1, 'MARCOS PAZ');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (101, 1, 'CARLOS TEJEDOR');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (102, 1, 'SAN PEDRO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (103, 1, 'GENERAL ALVARADO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (104, 1, 'SAN NICOLAS');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (105, 1, 'HIPOLITO YRIGOYEN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (106, 1, 'LAS FLORES');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (107, 1, 'CORONEL PRINGLES');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (108, 1, 'GENERAL SAN MARTIN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (109, 1, 'BENITO JUAREZ');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (110, 1, 'SAN CAYETANO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (111, 1, 'ADOLFO GONZALES CHAVES');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (112, 1, 'DOLORES');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (113, 1, 'SAN ANTONIO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (114, 1, 'LOBERIA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (115, 1, 'RAMALLO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (116, 1, 'GENERAL ALVEAR');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (117, 1, 'ENSENADA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (118, 1, 'TORDILLO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (119, 1, 'GENERAL GUIDO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (120, 1, 'GENERAL LAS HERAS');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (121, 1, 'GENERAL JUAN MADARIAGA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (122, 1, 'GENERAL LA MADRID');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (123, 1, 'GENERAL LAVALLE');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (124, 1, 'GENERAL RODRIGUEZ');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (125, 1, 'GENERAL VLLEGAS');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (126, 1, 'ADOLFO GONZALEZ CHAVES');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (127, 1, 'CORONEL DE MARINA L.ROSALES');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (128, 1, 'BOLIVAR');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (129, 1, 'SAN FERNANDO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (130, 1, 'CAPITAN SARMIENTO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (131, 1, 'ROQUE PEREZ');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (132, 1, 'MORENO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (133, 1, 'LAPRIDA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (134, 1, 'MAIPU');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (135, 1, 'ECHEVERRIA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (136, 1, 'PILAR');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (137, 1, 'CORONEL DE MARINA L. ROSALES');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (138, 1, 'SUIPACHA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (139, 1, 'SAN ANTONIO DE ARECO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (140, 1, 'BARAZATEGUI');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (141, 1, 'ALSINA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (142, 1, 'LEANDRO N. ELEM');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (143, 1, 'GRL.SAN MARTIN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (144, 1, 'CORONEL');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (145, 2, 'CAPAYAN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (146, 2, 'ANDALGALA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (147, 2, 'EL ALTO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (148, 2, 'SANTA ROSA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (149, 2, 'ANCASTI');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (150, 2, 'PACLIN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (151, 2, 'SANTA MARIA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (152, 2, 'TINOGASTA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (153, 2, 'LA PAZ');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (154, 2, 'VALLE VIEJO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (155, 2, 'ANTOFAGASTA DE LA SIERRA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (156, 2, 'BELEN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (157, 2, 'CAPITAL');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (158, 2, 'FRAY MAMERTO ESQUIU');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (159, 2, 'POMAN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (160, 2, 'AMBATO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (161, 3, 'INDEPENDENCIA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (162, 3, 'SAN FERNANDO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (163, 3, 'PRIMERO DE MAYO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (164, 3, 'FRAY JUSTO SANTA MARIA DE ORO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (165, 3, 'SARGENTO CABRAL');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (166, 3, 'GENERAL GUEMES');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (167, 3, 'TAPENAGA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (168, 3, 'CHACABUCO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (169, 3, 'LIBERTADOR GRL.SAN MARTIN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (170, 3, '25 DE MAYO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (171, 3, '12 DE OCTUBRE');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (172, 3, 'COMANDANTE FERNANDEZ');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (173, 3, 'QUITILIPI');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (174, 3, 'MAYOR LUIS J.FONTANA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (175, 3, 'LIBERTAD');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (176, 3, 'BERMEJO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (177, 3, 'ALMIRANTE BROWN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (178, 3, 'MEYOR LUIS J.FONTANA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (179, 3, 'GENERAL BELGRANO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (180, 3, 'LIBERTADOR GRL. SAN MARTIN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (181, 3, 'GENERAL DONOVAN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (182, 3, 'SAN LORENZO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (183, 3, 'LEBERTADOR GRL.SAN MARTIN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (184, 3, 'MAIPU');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (185, 3, 'OHIGGINS');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (186, 3, '9 DE JULIO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (187, 3, 'LIBERTADOR SAN MARTIN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (188, 4, 'RIO SENGUERR');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (189, 4, 'MARTIRES');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (190, 4, 'ESCALANTE');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (191, 4, 'GAIMAN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (192, 4, 'SARMIENTO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (193, 4, 'CUSHAMEN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (194, 4, 'FLORENTINO AMEGHINO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (195, 4, 'PASO DE INDIOS');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (196, 4, 'TELSEN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (197, 4, 'LANGUIÑEO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (198, 4, 'GASTRE');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (199, 4, 'FUTALEUFU');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (200, 4, 'TEHUELCHES');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (201, 4, 'RAWSON');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (202, 4, 'BIEDMA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (203, 5, 'RIO CUARTO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (204, 5, 'TOTORAL');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (205, 5, 'COLON');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (206, 5, 'MINAS');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (207, 5, 'PUNILLA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (208, 5, 'JUAREZ CELMAN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (209, 5, 'MARCOS JUAREZ');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (210, 5, 'SAN JUSTO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (211, 5, 'TERCERO ARRIBA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (212, 5, 'RIO SECO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (213, 5, 'CAPITAL');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (214, 5, 'SANTA MARIA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (215, 5, 'SAN ALBERTO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (216, 5, 'UNION');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (217, 5, 'POCHO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (218, 5, 'CALAMUCHITA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (219, 5, 'ISCHILIN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (220, 5, 'GENERAL SAN MARTIN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (221, 5, 'RIO PRIMERO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (222, 5, 'CRUZ DEL EJE');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (223, 5, 'GRL.ROCA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (224, 5, 'GENERAL ROCA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (225, 5, 'SOBREMONTE');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (226, 5, 'RIO SEGUNDO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (227, 5, 'TULUMBA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (228, 5, 'SAN JAVIER');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (229, 5, 'PRESIDENTE ROQUE SAEZ PEÑA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (230, 5, 'PRESIDENTE ROQUE SAENZ PEÑA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (232, 5, 'CRUZ DE EJE');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (233, 5, 'CORONEL PRINGLES');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (234, 5, 'RIO TERCERO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (235, 5, 'CVALAMUCHITA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (236, 6, 'SAN ROQUE');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (237, 6, 'MONTE CASEROS');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (238, 6, 'GENERAL ALVEAR');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (239, 6, 'CURUZU CUATIA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (240, 6, 'SAN MARTIN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (241, 6, 'MERCEDES');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (242, 6, 'SALADAS');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (243, 6, 'ITUZAINGO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (244, 6, 'BERON DE ASTRADA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (245, 6, 'BELLA VISTA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (246, 6, 'SAN LUIS DEL PALMAR');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (247, 6, 'CAPITAL');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (248, 6, 'LAVALLE');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (249, 6, 'PASO DE LOS LIBRES');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (250, 6, 'GOYA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (251, 6, 'EMPEDRADO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (252, 6, 'SAUCE');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (253, 6, 'GENERAL PAZ');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (254, 6, 'SANTO TOME');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (255, 6, 'SAN MIGUEL');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (256, 6, 'CONCEPCION');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (257, 6, 'ESQUINA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (258, 6, 'SAN COSME');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (259, 6, 'ITATI');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (260, 6, 'MBURUCUYA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (261, 7, 'URUGUAY');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (262, 7, 'NOGOYA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (263, 7, 'TALA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (264, 7, 'GUALEGUAY');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (265, 7, 'DIAMANTE');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (266, 7, 'PARANA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (267, 7, 'GUALEGUAYCHU');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (268, 7, 'COLON');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (269, 7, 'VICTORIA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (270, 7, 'VILLAGUAY');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (271, 7, 'FELICIANO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (272, 7, 'CONCORDIA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (273, 7, 'LA PAZ');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (274, 7, 'FEDERACION');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (275, 7, 'FEDERAL');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (276, 7, 'CASTELLANOS');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (277, 8, 'PILAGAS');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (278, 8, 'PATIÑO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (279, 8, 'PILCOMAYO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (280, 8, 'BERMEJO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (281, 8, 'PIRANE');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (282, 8, 'FORMOSA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (283, 8, 'MATACOS');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (284, 8, 'RAMON LISTA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (285, 8, 'PILLAGAS');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (286, 8, 'LAISHI');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (287, 9, 'LEDESMA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (288, 9, 'COCHINOCA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (289, 9, 'EL CARMEN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (290, 9, 'TUMBAYA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (291, 9, 'CAPITAL');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (292, 9, 'YAVI');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (293, 9, 'HUMAHUACA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (294, 9, 'RINCONADA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (295, 9, 'VALLE GRANDE');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (296, 9, 'SUSQUES');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (297, 9, 'SANTA CATALINA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (298, 9, 'SAN ANTONIO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (299, 9, 'SANTA BARBARA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (300, 9, 'SAN PEDRO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (301, 9, 'TILCARA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (302, 9, 'LADESMA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (303, 10, 'HUCAL');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (304, 10, 'REALICO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (305, 10, 'MARA CO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (306, 10, 'QUEMUQUEMU');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (307, 10, 'CHICAL CO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (308, 10, 'GUATRACHE');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (309, 10, 'CAPITAL');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (310, 10, 'CALEUCALEU');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (311, 10, 'TRENEL');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (312, 10, 'UTRACAN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (313, 10, 'ATREUCO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (314, 10, 'TOAY');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (315, 10, 'CHAPADLEUFU');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (316, 10, 'CONELO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (317, 10, 'PUELEN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (318, 10, 'RANCUL');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (319, 10, 'QUEMU QUEMU');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (320, 10, 'LOVENTUE');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (321, 10, 'CONHELO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (322, 10, 'CATRILO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (323, 10, 'CHAPALEUFU');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (324, 10, 'ULTRACAN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (325, 10, 'CHALILEO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (326, 10, 'LIHUEL CALEL');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (327, 10, 'MARACO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (328, 10, 'CALEU CALEU');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (329, 10, 'CURACO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (330, 10, 'LIMAY MAHUIDA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (331, 11, 'CASTRO BARROS');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (332, 11, 'GENERAL SAN MARTIN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (333, 11, 'GENERAL LAVALLE');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (334, 11, 'ARAUCO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (335, 11, 'GRAL.ANGEL V.PEÑALOZA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (336, 11, 'SAN BLAS DE LOS SAUCES');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (337, 11, 'INDEPENDENCIA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (338, 11, 'GENERAL OCAMPO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (339, 11, 'CHILECITO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (340, 11, 'FAMATINA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (341, 11, 'GRL.JUAN FACUNDO QUIROGA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (342, 11, 'GRL.ANGEL V. PEÑALOZA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (343, 11, 'GENERAL BELGRANO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (344, 11, 'GENERAL SARMIENTO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (345, 11, 'CAPITAL');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (346, 11, 'GDOR. GORDILLO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (347, 11, 'GENERAL ANGEL VICENTE PEÑALOZA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (348, 11, 'GOBERNADOR GORDILLO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (349, 11, 'ROSARIO VERA PEÑALOZA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (350, 11, 'GRL.SAN MARTIN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (351, 11, 'GENERAL LA MADRID');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (352, 11, 'GENERAL JUAN FACUNDO QUIROGA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (353, 11, 'GENERALOCAMPO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (354, 11, 'SANAGASTA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (355, 12, 'SAN RAFAEL');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (356, 12, 'LUJAN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (357, 12, 'MALARGUE');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (358, 12, 'GUAYMALLEN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (359, 12, 'LAVALLE');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (360, 12, 'JUNIN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (361, 12, 'TUPUNGATO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (362, 12, 'RIVADAVIA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (363, 12, 'MAIPU');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (364, 12, 'GODOY CRUZ');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (365, 12, 'GENERAL ALVEAR');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (366, 12, 'LA PAZ');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (367, 12, 'TUNUYAN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (368, 12, 'SAN CARLOS');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (369, 12, 'LAS HERAS');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (370, 12, 'LUJAN DE CUYO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (371, 12, 'SAN MARTIN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (372, 12, 'SANTA ROSA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (373, 12, 'CAPITAL');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (374, 13, '25 DE MAYO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (375, 13, 'IGUAZU');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (376, 13, 'EL DORADO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (377, 13, 'LEANDRO N. ALEM');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (378, 13, 'APOSTOLES');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (379, 13, 'CAINGUAS');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (380, 13, 'LEANDRO N.ALEM');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (381, 13, 'CONCEPCION');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (382, 13, 'SAN PEDRO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (383, 13, 'CANDELARIA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (384, 13, 'GRL.MANUEL BELGRANO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (385, 13, 'OBERA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (386, 13, 'LIBERTADOR GRL.SAN MARTIN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (387, 13, 'SAN IGNACIO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (388, 13, 'MONTECARLO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (389, 13, 'GENERAL MANUEL BELGRANO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (390, 13, 'LEBERTADOR GRL.SAN MARTIN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (391, 13, 'EL GUARANI');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (392, 13, 'ELDORADO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (393, 13, 'CAPITAL');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (394, 13, 'GUARANI');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (395, 13, 'SAN JAVIER');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (396, 13, 'LIBERTADOR GRL. SAN MARTIN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (397, 14, 'COLLON CURA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (398, 14, 'ALUMINE');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (399, 14, 'MINAS');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (400, 14, 'AÑELO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (401, 14, 'CONFLUENCIA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (402, 14, 'CHOS MALAL');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (403, 14, 'PICUNCHES');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (404, 14, 'NORQUIN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (405, 14, 'PEHUENCHES');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (406, 14, 'LONCOPUE');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (407, 14, 'HUILICHES');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (408, 14, 'ZAPALA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (409, 14, 'CATAN LIL');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (410, 14, 'ÑORQUIN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (411, 14, 'LOS LAGOS');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (412, 14, 'PICUN LEUFU');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (413, 14, 'LACAR');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (414, 14, 'ÑOEQUIN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (415, 15, 'VALCHETA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (416, 15, '25 DE MAYO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (417, 15, 'EL CUY');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (418, 15, 'ÑORQUINCO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (419, 15, 'GENERAL ROCA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (420, 15, 'AVELLANEDA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (421, 15, 'CONESA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (422, 15, 'PICHI MAHUIDA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (423, 15, 'SAN ANTONIO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (424, 15, 'PILCANIYEU');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (425, 15, '9 DE JULIO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (426, 15, 'ADOLFO ALSINA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (427, 15, 'BARILOCHE');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (428, 15, 'PIHI MAHUIDA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (429, 16, 'LA VIÑA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (430, 16, 'SAN MARTIN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (431, 16, 'ORAN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (432, 16, 'ANTA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (433, 16, 'GRAL.JOSE DE SAN MARTIN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (434, 16, 'GUACHIPAS');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (435, 16, 'ROSARIO DE LA FRONTERA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (436, 16, 'RIVADAVIA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (437, 16, 'METAN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (438, 16, 'SAN CARLOS');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (439, 16, 'GRL.GUEMES');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (440, 16, 'CACHI');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (441, 16, 'ROSARIO DE LERMA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (442, 16, 'CAFAYATE');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (443, 16, 'LOS ANDES');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (444, 16, 'GRL.JOSE DE SAN MARTIN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (445, 16, 'CAPITAL');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (446, 16, 'GRL.SAN MARTIN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (447, 16, 'GENERAL GUEMES');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (448, 16, 'CERRILLOS');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (449, 16, 'CHICOANA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (450, 16, 'LA POMA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (451, 16, 'LA CAPITAL');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (452, 16, 'CANDELARIA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (453, 16, 'ROSARIO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (454, 16, 'IRUYA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (455, 16, 'LA CALDERA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (456, 16, 'LOA ANDES');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (457, 16, 'MOLINOS');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (458, 16, 'SANTA VICTORIA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (459, 17, '9 DE JULIO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (460, 17, 'JACHAL');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (461, 17, 'ALBARDON');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (462, 17, '25 DE MAYO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (463, 17, 'SANTA LUCIA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (464, 17, 'ANGACO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (465, 17, 'IGLESIA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (466, 17, 'VALLE FERTIL');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (467, 17, 'CALINGASTA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (468, 17, 'RIVADAVIA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (469, 17, 'CAUCETE');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (470, 17, 'SARMIENTO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (471, 17, 'POCITO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (472, 17, 'SAN MARTIN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (473, 17, 'CHIMBAS');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (474, 17, 'IGLESIAS');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (475, 17, 'ULLUN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (476, 17, 'RAWSON');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (477, 17, 'CAPITAL');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (478, 17, 'ZONDA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (479, 18, 'BELGRANO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (480, 18, 'CHACABUCO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (481, 18, 'LA CAPITAL');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (482, 18, 'GOBERNADOR DUPUY');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (483, 18, 'GRL.PEDERNERA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (484, 18, 'AYACUCHO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (485, 18, 'JUNIN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (486, 18, 'GONERNADOR DUPUY');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (487, 18, 'CORONEL PRINGLES');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (488, 18, 'GENERAL PEDERNERA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (489, 18, 'GOBERNADOR DUVAL');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (490, 18, 'IGLESIA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (491, 18, 'LIBERTADOR GRL. SAN MARTIN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (492, 18, 'LIBERTADOR GRL.SAN MARTIN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (493, 18, 'LIBERTADOR GR.SAN MARTIN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (494, 18, 'CAUCETE');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (495, 19, 'GUER AIKE');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (496, 19, 'DESEADO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (497, 19, 'RIO CHICO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (498, 19, 'MAGALLANES');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (499, 19, 'LAGO ARGENTINO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (500, 19, 'CORPEN AIKE');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (501, 19, 'LAGO BUENOS AIRES');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (502, 20, 'GENERAL LOPEZ');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (503, 20, 'ROSARIO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (504, 20, 'GENERAL OBLIGADO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (505, 20, 'CONSTITUCION');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (506, 20, 'SAN LORENZO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (507, 20, 'SAN JAVIER');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (508, 20, 'LA CAPITAL');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (509, 20, 'SAN CRISTOBAL');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (510, 20, 'IRIONDO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (511, 20, 'CASTELLANOS');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (512, 20, 'NUEVE DE JULIO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (513, 20, 'CASEROS');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (514, 20, 'SAN JERONIMO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (515, 20, 'BELGRANO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (516, 20, 'CAPITAL');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (517, 20, 'SAN JUSTO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (518, 20, 'GRL.OBLIGADO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (519, 20, 'LA CAPUTAL');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (520, 20, 'GRL.LOPEZ');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (521, 20, 'VERA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (522, 20, '9 DE JULIO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (523, 20, 'SAN MARTIN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (524, 20, 'LAS COLONIAS');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (525, 20, 'GARAY');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (526, 20, 'CASTELANOS');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (527, 20, 'LAS COLINAS');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (528, 21, 'BANDA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (529, 21, 'MORENO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (530, 21, 'ALBERDI');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (531, 21, 'PELLEGRINI');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (532, 21, 'OJO DE AGUA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (533, 21, 'RIO HONDO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (534, 21, 'GENERAL TABOADA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (535, 21, 'CHOYA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (536, 21, 'CAPITAL');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (537, 21, 'AGUIRRE');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (538, 21, 'SILIPICA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (539, 21, 'BELGRANO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (540, 21, 'FIGUEROA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (541, 21, 'SALAVINA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (542, 21, 'QUEBRACHOS');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (543, 21, 'ROBLES');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (544, 21, 'AVELLANEDA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (545, 21, 'JIMENEZ');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (546, 21, 'ATAMISQUI');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (547, 21, 'SAN MARTIN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (548, 21, 'MATARA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (549, 21, 'SALAYINA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (550, 21, 'GUASAYAN');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (551, 21, 'COPO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (552, 21, 'BRIGADIER JUAN FELIPE IBARRA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (553, 21, 'DOBLES');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (554, 21, 'SARMIENTO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (555, 21, 'LORETO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (556, 21, 'MITRE');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (557, 21, 'RIVADAVIA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (558, 22, 'USHUAIA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (559, 22, 'ISLAS DEL ATLANTICO SUR');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (560, 22, 'SECTOR ANTARTICO ARGENTINO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (561, 22, 'RIO GRANDE');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (562, 22, 'IS.DEL ATLANTICO SUR E IS.MALVINAS');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (563, 22, 'ANTARTIDA ARGENTINA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (564, 23, 'BURRUYACU');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (565, 23, 'TRANCAS');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (566, 23, 'MONTEROS');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (567, 23, 'LEALES');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (568, 23, 'CRUZ ALTA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (569, 23, 'RIO CHICO');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (570, 23, 'CHICLIGASTA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (571, 23, 'TAFI');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (572, 23, 'GRANEROS');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (573, 23, 'FAMAILLA');
INSERT INTO departamentos (id, provincia_id, nombre) VALUES (574, 23, 'CAPITAL');
