insert into partidos (id, provincia, name) values (1, 1, 'azul');
insert into partidos (id, provincia, name) values (2, 1, 'puan');
insert into partidos (id, provincia, name) values (3, 1, 'la matanza');
insert into partidos (id, provincia, name) values (4, 1, 'tigre');
insert into partidos (id, provincia, name) values (5, 1, '25 de mayo');
insert into partidos (id, provincia, name) values (6, 1, 'trenque lauquen');
insert into partidos (id, provincia, name) values (7, 1, '9 de julio');
insert into partidos (id, provincia, name) values (8, 1, 'lanus');
insert into partidos (id, provincia, name) values (9, 1, 'la plata');
insert into partidos (id, provincia, name) values (10, 1, 'monte');
insert into partidos (id, provincia, name) values (11, 1, 'pehuajo');
insert into partidos (id, provincia, name) values (12, 1, 'san isidro');
insert into partidos (id, provincia, name) values (13, 1, 'pergamino');
insert into partidos (id, provincia, name) values (14, 1, 'alberti');
insert into partidos (id, provincia, name) values (15, 1, 'chascomus');
insert into partidos (id, provincia, name) values (16, 1, 'esteban echeverria');
insert into partidos (id, provincia, name) values (17, 1, 'mercedes');
insert into partidos (id, provincia, name) values (18, 1, 'bahia blanca');
insert into partidos (id, provincia, name) values (19, 1, 'merlo');
insert into partidos (id, provincia, name) values (20, 1, 'junin');
insert into partidos (id, provincia, name) values (21, 1, 'guamini');
insert into partidos (id, provincia, name) values (22, 1, 'lujan');
insert into partidos (id, provincia, name) values (23, 1, 'leandro n.alem');
insert into partidos (id, provincia, name) values (24, 1, 'matanza');
insert into partidos (id, provincia, name) values (25, 1, 'general paz');
insert into partidos (id, provincia, name) values (26, 1, 'san vicente');
insert into partidos (id, provincia, name) values (27, 1, 'cañuelas');
insert into partidos (id, provincia, name) values (28, 1, 'almirante brown');
insert into partidos (id, provincia, name) values (29, 1, 'cnl.de marina  l.rosales');
insert into partidos (id, provincia, name) values (30, 1, 'baradero');
insert into partidos (id, provincia, name) values (31, 1, 'saavedra');
insert into partidos (id, provincia, name) values (32, 1, 'brandsen');
insert into partidos (id, provincia, name) values (33, 1, 'general sarmiento');
insert into partidos (id, provincia, name) values (34, 1, 'tapalque');
insert into partidos (id, provincia, name) values (35, 1, 'saladillo');
insert into partidos (id, provincia, name) values (36, 1, 'magdalena');
insert into partidos (id, provincia, name) values (37, 1, 'gonzales chaves');
insert into partidos (id, provincia, name) values (38, 1, 'general pinto');
insert into partidos (id, provincia, name) values (39, 1, 'navarro');
insert into partidos (id, provincia, name) values (40, 1, 'daireaux');
insert into partidos (id, provincia, name) values (41, 1, 'lobos');
insert into partidos (id, provincia, name) values (42, 1, 'coronel dorrego');
insert into partidos (id, provincia, name) values (43, 1, 'adolfo alsina');
insert into partidos (id, provincia, name) values (44, 1, 'colon');
insert into partidos (id, provincia, name) values (45, 1, 'general arenales');
insert into partidos (id, provincia, name) values (46, 1, 'lincoln');
insert into partidos (id, provincia, name) values (47, 1, 'villarino');
insert into partidos (id, provincia, name) values (48, 1, 'vicente lopez');
insert into partidos (id, provincia, name) values (49, 1, 'bartolome mitre');
insert into partidos (id, provincia, name) values (50, 1, 'exaltacion de la cruz');
insert into partidos (id, provincia, name) values (51, 1, 'salto');
insert into partidos (id, provincia, name) values (52, 1, 'bragado');
insert into partidos (id, provincia, name) values (53, 1, 'zarate');
insert into partidos (id, provincia, name) values (54, 1, 'avellaneda');
insert into partidos (id, provincia, name) values (55, 1, 'ayacucho');
insert into partidos (id, provincia, name) values (56, 1, 'san andres de giles');
insert into partidos (id, provincia, name) values (57, 1, 'tandil');
insert into partidos (id, provincia, name) values (58, 1, 'rivadavia');
insert into partidos (id, provincia, name) values (59, 1, 'patagones');
insert into partidos (id, provincia, name) values (60, 1, 'grl.viamonte');
insert into partidos (id, provincia, name) values (61, 1, 'cnl.de marina leonardo rosales');
insert into partidos (id, provincia, name) values (62, 1, 'balcarce');
insert into partidos (id, provincia, name) values (63, 1, 'tres arroyos');
insert into partidos (id, provincia, name) values (64, 1, 'general villegas');
insert into partidos (id, provincia, name) values (65, 1, 'lomas de zamora');
insert into partidos (id, provincia, name) values (66, 1, 'berisso');
insert into partidos (id, provincia, name) values (67, 1, 'juarez');
insert into partidos (id, provincia, name) values (68, 1, 'grl.pueyrredon');
insert into partidos (id, provincia, name) values (69, 1, 'coronel suarez');
insert into partidos (id, provincia, name) values (70, 1, 'escobar');
insert into partidos (id, provincia, name) values (71, 1, 'carlos casares');
insert into partidos (id, provincia, name) values (72, 1, 'chivilcoy');
insert into partidos (id, provincia, name) values (73, 1, 'berazategui');
insert into partidos (id, provincia, name) values (74, 1, 'quilmes');
insert into partidos (id, provincia, name) values (75, 1, 'torquinst');
insert into partidos (id, provincia, name) values (76, 1, '3 de febrero');
insert into partidos (id, provincia, name) values (77, 1, 'olavarria');
insert into partidos (id, provincia, name) values (78, 1, 'pellegrini');
insert into partidos (id, provincia, name) values (79, 1, 'general belgano');
insert into partidos (id, provincia, name) values (80, 1, 'florencio varela');
insert into partidos (id, provincia, name) values (81, 1, 'salliquelo');
insert into partidos (id, provincia, name) values (82, 1, 'cnl.de marina l.rosales');
insert into partidos (id, provincia, name) values (83, 1, 'mar chiquita');
insert into partidos (id, provincia, name) values (84, 1, 'general pueyrredon');
insert into partidos (id, provincia, name) values (85, 1, 'campana');
insert into partidos (id, provincia, name) values (86, 1, 'grl.sarmiento');
insert into partidos (id, provincia, name) values (87, 1, 'rojas');
insert into partidos (id, provincia, name) values (88, 1, 'sarmiento');
insert into partidos (id, provincia, name) values (89, 1, 'carmen de areco');
insert into partidos (id, provincia, name) values (90, 1, 'pila');
insert into partidos (id, provincia, name) values (91, 1, 'tres de febrero');
insert into partidos (id, provincia, name) values (92, 1, 'moron');
insert into partidos (id, provincia, name) values (93, 1, 'castelli');
insert into partidos (id, provincia, name) values (94, 1, 'chacabuco');
insert into partidos (id, provincia, name) values (95, 1, 'general viamonte');
insert into partidos (id, provincia, name) values (96, 1, 'rauch');
insert into partidos (id, provincia, name) values (97, 1, 'general belgrano');
insert into partidos (id, provincia, name) values (98, 1, 'tornquist');
insert into partidos (id, provincia, name) values (99, 1, 'necochea');
insert into partidos (id, provincia, name) values (100, 1, 'marcos paz');
insert into partidos (id, provincia, name) values (101, 1, 'carlos tejedor');
insert into partidos (id, provincia, name) values (102, 1, 'san pedro');
insert into partidos (id, provincia, name) values (103, 1, 'general alvarado');
insert into partidos (id, provincia, name) values (104, 1, 'san nicolas');
insert into partidos (id, provincia, name) values (105, 1, 'hipolito yrigoyen');
insert into partidos (id, provincia, name) values (106, 1, 'las flores');
insert into partidos (id, provincia, name) values (107, 1, 'coronel pringles');
insert into partidos (id, provincia, name) values (108, 1, 'general san martin');
insert into partidos (id, provincia, name) values (109, 1, 'benito juarez');
insert into partidos (id, provincia, name) values (110, 1, 'san cayetano');
insert into partidos (id, provincia, name) values (111, 1, 'adolfo gonzales chaves');
insert into partidos (id, provincia, name) values (112, 1, 'dolores');
insert into partidos (id, provincia, name) values (113, 1, 'san antonio');
insert into partidos (id, provincia, name) values (114, 1, 'loberia');
insert into partidos (id, provincia, name) values (115, 1, 'ramallo');
insert into partidos (id, provincia, name) values (116, 1, 'general alvear');
insert into partidos (id, provincia, name) values (117, 1, 'ensenada');
insert into partidos (id, provincia, name) values (118, 1, 'tordillo');
insert into partidos (id, provincia, name) values (119, 1, 'general guido');
insert into partidos (id, provincia, name) values (120, 1, 'general las heras');
insert into partidos (id, provincia, name) values (121, 1, 'general juan madariaga');
insert into partidos (id, provincia, name) values (122, 1, 'general la madrid');
insert into partidos (id, provincia, name) values (123, 1, 'general lavalle');
insert into partidos (id, provincia, name) values (124, 1, 'general rodriguez');
insert into partidos (id, provincia, name) values (125, 1, 'general vllegas');
insert into partidos (id, provincia, name) values (126, 1, 'adolfo gonzalez chaves');
insert into partidos (id, provincia, name) values (127, 1, 'coronel de marina l.rosales');
insert into partidos (id, provincia, name) values (128, 1, 'bolivar');
insert into partidos (id, provincia, name) values (129, 1, 'san fernando');
insert into partidos (id, provincia, name) values (130, 1, 'capitan sarmiento');
insert into partidos (id, provincia, name) values (131, 1, 'roque perez');
insert into partidos (id, provincia, name) values (132, 1, 'moreno');
insert into partidos (id, provincia, name) values (133, 1, 'laprida');
insert into partidos (id, provincia, name) values (134, 1, 'maipu');
insert into partidos (id, provincia, name) values (135, 1, 'echeverria');
insert into partidos (id, provincia, name) values (136, 1, 'pilar');
insert into partidos (id, provincia, name) values (137, 1, 'coronel de marina l. rosales');
insert into partidos (id, provincia, name) values (138, 1, 'suipacha');
insert into partidos (id, provincia, name) values (139, 1, 'san antonio de areco');
insert into partidos (id, provincia, name) values (140, 1, 'barazategui');
insert into partidos (id, provincia, name) values (141, 1, 'alsina');
insert into partidos (id, provincia, name) values (142, 1, 'leandro n. elem');
insert into partidos (id, provincia, name) values (143, 1, 'grl.san martin');
insert into partidos (id, provincia, name) values (144, 1, 'coronel');
insert into partidos (id, provincia, name) values (145, 2, 'capayan');
insert into partidos (id, provincia, name) values (146, 2, 'andalgala');
insert into partidos (id, provincia, name) values (147, 2, 'el alto');
insert into partidos (id, provincia, name) values (148, 2, 'santa rosa');
insert into partidos (id, provincia, name) values (149, 2, 'ancasti');
insert into partidos (id, provincia, name) values (150, 2, 'paclin');
insert into partidos (id, provincia, name) values (151, 2, 'santa maria');
insert into partidos (id, provincia, name) values (152, 2, 'tinogasta');
insert into partidos (id, provincia, name) values (153, 2, 'la paz');
insert into partidos (id, provincia, name) values (154, 2, 'valle viejo');
insert into partidos (id, provincia, name) values (155, 2, 'antofagasta de la sierra');
insert into partidos (id, provincia, name) values (156, 2, 'belen');
insert into partidos (id, provincia, name) values (157, 2, 'capital');
insert into partidos (id, provincia, name) values (158, 2, 'fray mamerto esquiu');
insert into partidos (id, provincia, name) values (159, 2, 'poman');
insert into partidos (id, provincia, name) values (160, 2, 'ambato');
insert into partidos (id, provincia, name) values (161, 3, 'independencia');
insert into partidos (id, provincia, name) values (162, 3, 'san fernando');
insert into partidos (id, provincia, name) values (163, 3, 'primero de mayo');
insert into partidos (id, provincia, name) values (164, 3, 'fray justo santa maria de oro');
insert into partidos (id, provincia, name) values (165, 3, 'sargento cabral');
insert into partidos (id, provincia, name) values (166, 3, 'general guemes');
insert into partidos (id, provincia, name) values (167, 3, 'tapenaga');
insert into partidos (id, provincia, name) values (168, 3, 'chacabuco');
insert into partidos (id, provincia, name) values (169, 3, 'libertador grl.san martin');
insert into partidos (id, provincia, name) values (170, 3, '25 de mayo');
insert into partidos (id, provincia, name) values (171, 3, '12 de octubre');
insert into partidos (id, provincia, name) values (172, 3, 'comandante fernandez');
insert into partidos (id, provincia, name) values (173, 3, 'quitilipi');
insert into partidos (id, provincia, name) values (174, 3, 'mayor luis j.fontana');
insert into partidos (id, provincia, name) values (175, 3, 'libertad');
insert into partidos (id, provincia, name) values (176, 3, 'bermejo');
insert into partidos (id, provincia, name) values (177, 3, 'almirante brown');
insert into partidos (id, provincia, name) values (178, 3, 'meyor luis j.fontana');
insert into partidos (id, provincia, name) values (179, 3, 'general belgrano');
insert into partidos (id, provincia, name) values (180, 3, 'libertador grl. san martin');
insert into partidos (id, provincia, name) values (181, 3, 'general donovan');
insert into partidos (id, provincia, name) values (182, 3, 'san lorenzo');
insert into partidos (id, provincia, name) values (183, 3, 'lebertador grl.san martin');
insert into partidos (id, provincia, name) values (184, 3, 'maipu');
insert into partidos (id, provincia, name) values (185, 3, 'ohiggins');
insert into partidos (id, provincia, name) values (186, 3, '9 de julio');
insert into partidos (id, provincia, name) values (187, 3, 'libertador san martin');
insert into partidos (id, provincia, name) values (188, 4, 'rio senguerr');
insert into partidos (id, provincia, name) values (189, 4, 'martires');
insert into partidos (id, provincia, name) values (190, 4, 'escalante');
insert into partidos (id, provincia, name) values (191, 4, 'gaiman');
insert into partidos (id, provincia, name) values (192, 4, 'sarmiento');
insert into partidos (id, provincia, name) values (193, 4, 'cushamen');
insert into partidos (id, provincia, name) values (194, 4, 'florentino ameghino');
insert into partidos (id, provincia, name) values (195, 4, 'paso de indios');
insert into partidos (id, provincia, name) values (196, 4, 'telsen');
insert into partidos (id, provincia, name) values (197, 4, 'languiñeo');
insert into partidos (id, provincia, name) values (198, 4, 'gastre');
insert into partidos (id, provincia, name) values (199, 4, 'futaleufu');
insert into partidos (id, provincia, name) values (200, 4, 'tehuelches');
insert into partidos (id, provincia, name) values (201, 4, 'rawson');
insert into partidos (id, provincia, name) values (202, 4, 'biedma');
insert into partidos (id, provincia, name) values (203, 5, 'rio cuarto');
insert into partidos (id, provincia, name) values (204, 5, 'totoral');
insert into partidos (id, provincia, name) values (205, 5, 'colon');
insert into partidos (id, provincia, name) values (206, 5, 'minas');
insert into partidos (id, provincia, name) values (207, 5, 'punilla');
insert into partidos (id, provincia, name) values (208, 5, 'juarez celman');
insert into partidos (id, provincia, name) values (209, 5, 'marcos juarez');
insert into partidos (id, provincia, name) values (210, 5, 'san justo');
insert into partidos (id, provincia, name) values (211, 5, 'tercero arriba');
insert into partidos (id, provincia, name) values (212, 5, 'rio seco');
insert into partidos (id, provincia, name) values (213, 5, 'capital');
insert into partidos (id, provincia, name) values (214, 5, 'santa maria');
insert into partidos (id, provincia, name) values (215, 5, 'san alberto');
insert into partidos (id, provincia, name) values (216, 5, 'union');
insert into partidos (id, provincia, name) values (217, 5, 'pocho');
insert into partidos (id, provincia, name) values (218, 5, 'calamuchita');
insert into partidos (id, provincia, name) values (219, 5, 'ischilin');
insert into partidos (id, provincia, name) values (220, 5, 'general san martin');
insert into partidos (id, provincia, name) values (221, 5, 'rio primero');
insert into partidos (id, provincia, name) values (222, 5, 'cruz del eje');
insert into partidos (id, provincia, name) values (223, 5, 'grl.roca');
insert into partidos (id, provincia, name) values (224, 5, 'general roca');
insert into partidos (id, provincia, name) values (225, 5, 'sobremonte');
insert into partidos (id, provincia, name) values (226, 5, 'rio segundo');
insert into partidos (id, provincia, name) values (227, 5, 'tulumba');
insert into partidos (id, provincia, name) values (228, 5, 'san javier');
insert into partidos (id, provincia, name) values (229, 5, 'presidente roque saez peña');
insert into partidos (id, provincia, name) values (230, 5, 'presidente roque saenz peña');
insert into partidos (id, provincia, name) values (232, 5, 'cruz de eje');
insert into partidos (id, provincia, name) values (233, 5, 'coronel pringles');
insert into partidos (id, provincia, name) values (234, 5, 'rio tercero');
insert into partidos (id, provincia, name) values (235, 5, 'cvalamuchita');
insert into partidos (id, provincia, name) values (236, 6, 'san roque');
insert into partidos (id, provincia, name) values (237, 6, 'monte caseros');
insert into partidos (id, provincia, name) values (238, 6, 'general alvear');
insert into partidos (id, provincia, name) values (239, 6, 'curuzu cuatia');
insert into partidos (id, provincia, name) values (240, 6, 'san martin');
insert into partidos (id, provincia, name) values (241, 6, 'mercedes');
insert into partidos (id, provincia, name) values (242, 6, 'saladas');
insert into partidos (id, provincia, name) values (243, 6, 'ituzaingo');
insert into partidos (id, provincia, name) values (244, 6, 'beron de astrada');
insert into partidos (id, provincia, name) values (245, 6, 'bella vista');
insert into partidos (id, provincia, name) values (246, 6, 'san luis del palmar');
insert into partidos (id, provincia, name) values (247, 6, 'capital');
insert into partidos (id, provincia, name) values (248, 6, 'lavalle');
insert into partidos (id, provincia, name) values (249, 6, 'paso de los libres');
insert into partidos (id, provincia, name) values (250, 6, 'goya');
insert into partidos (id, provincia, name) values (251, 6, 'empedrado');
insert into partidos (id, provincia, name) values (252, 6, 'sauce');
insert into partidos (id, provincia, name) values (253, 6, 'general paz');
insert into partidos (id, provincia, name) values (254, 6, 'santo tome');
insert into partidos (id, provincia, name) values (255, 6, 'san miguel');
insert into partidos (id, provincia, name) values (256, 6, 'concepcion');
insert into partidos (id, provincia, name) values (257, 6, 'esquina');
insert into partidos (id, provincia, name) values (258, 6, 'san cosme');
insert into partidos (id, provincia, name) values (259, 6, 'itati');
insert into partidos (id, provincia, name) values (260, 6, 'mburucuya');
insert into partidos (id, provincia, name) values (261, 7, 'uruguay');
insert into partidos (id, provincia, name) values (262, 7, 'nogoya');
insert into partidos (id, provincia, name) values (263, 7, 'tala');
insert into partidos (id, provincia, name) values (264, 7, 'gualeguay');
insert into partidos (id, provincia, name) values (265, 7, 'diamante');
insert into partidos (id, provincia, name) values (266, 7, 'parana');
insert into partidos (id, provincia, name) values (267, 7, 'gualeguaychu');
insert into partidos (id, provincia, name) values (268, 7, 'colon');
insert into partidos (id, provincia, name) values (269, 7, 'victoria');
insert into partidos (id, provincia, name) values (270, 7, 'villaguay');
insert into partidos (id, provincia, name) values (271, 7, 'feliciano');
insert into partidos (id, provincia, name) values (272, 7, 'concordia');
insert into partidos (id, provincia, name) values (273, 7, 'la paz');
insert into partidos (id, provincia, name) values (274, 7, 'federacion');
insert into partidos (id, provincia, name) values (275, 7, 'federal');
insert into partidos (id, provincia, name) values (276, 7, 'castellanos');
insert into partidos (id, provincia, name) values (277, 8, 'pilagas');
insert into partidos (id, provincia, name) values (278, 8, 'patiño');
insert into partidos (id, provincia, name) values (279, 8, 'pilcomayo');
insert into partidos (id, provincia, name) values (280, 8, 'bermejo');
insert into partidos (id, provincia, name) values (281, 8, 'pirane');
insert into partidos (id, provincia, name) values (282, 8, 'formosa');
insert into partidos (id, provincia, name) values (283, 8, 'matacos');
insert into partidos (id, provincia, name) values (284, 8, 'ramon lista');
insert into partidos (id, provincia, name) values (285, 8, 'pillagas');
insert into partidos (id, provincia, name) values (286, 8, 'laishi');
insert into partidos (id, provincia, name) values (287, 9, 'ledesma');
insert into partidos (id, provincia, name) values (288, 9, 'cochinoca');
insert into partidos (id, provincia, name) values (289, 9, 'el carmen');
insert into partidos (id, provincia, name) values (290, 9, 'tumbaya');
insert into partidos (id, provincia, name) values (291, 9, 'capital');
insert into partidos (id, provincia, name) values (292, 9, 'yavi');
insert into partidos (id, provincia, name) values (293, 9, 'humahuaca');
insert into partidos (id, provincia, name) values (294, 9, 'rinconada');
insert into partidos (id, provincia, name) values (295, 9, 'valle grande');
insert into partidos (id, provincia, name) values (296, 9, 'susques');
insert into partidos (id, provincia, name) values (297, 9, 'santa catalina');
insert into partidos (id, provincia, name) values (298, 9, 'san antonio');
insert into partidos (id, provincia, name) values (299, 9, 'santa barbara');
insert into partidos (id, provincia, name) values (300, 9, 'san pedro');
insert into partidos (id, provincia, name) values (301, 9, 'tilcara');
insert into partidos (id, provincia, name) values (302, 9, 'ladesma');
insert into partidos (id, provincia, name) values (303, 10, 'hucal');
insert into partidos (id, provincia, name) values (304, 10, 'realico');
insert into partidos (id, provincia, name) values (305, 10, 'mara co');
insert into partidos (id, provincia, name) values (306, 10, 'quemuquemu');
insert into partidos (id, provincia, name) values (307, 10, 'chical co');
insert into partidos (id, provincia, name) values (308, 10, 'guatrache');
insert into partidos (id, provincia, name) values (309, 10, 'capital');
insert into partidos (id, provincia, name) values (310, 10, 'caleucaleu');
insert into partidos (id, provincia, name) values (311, 10, 'trenel');
insert into partidos (id, provincia, name) values (312, 10, 'utracan');
insert into partidos (id, provincia, name) values (313, 10, 'atreuco');
insert into partidos (id, provincia, name) values (314, 10, 'toay');
insert into partidos (id, provincia, name) values (315, 10, 'chapadleufu');
insert into partidos (id, provincia, name) values (316, 10, 'conelo');
insert into partidos (id, provincia, name) values (317, 10, 'puelen');
insert into partidos (id, provincia, name) values (318, 10, 'rancul');
insert into partidos (id, provincia, name) values (319, 10, 'quemu quemu');
insert into partidos (id, provincia, name) values (320, 10, 'loventue');
insert into partidos (id, provincia, name) values (321, 10, 'conhelo');
insert into partidos (id, provincia, name) values (322, 10, 'catrilo');
insert into partidos (id, provincia, name) values (323, 10, 'chapaleufu');
insert into partidos (id, provincia, name) values (324, 10, 'ultracan');
insert into partidos (id, provincia, name) values (325, 10, 'chalileo');
insert into partidos (id, provincia, name) values (326, 10, 'lihuel calel');
insert into partidos (id, provincia, name) values (327, 10, 'maraco');
insert into partidos (id, provincia, name) values (328, 10, 'caleu caleu');
insert into partidos (id, provincia, name) values (329, 10, 'curaco');
insert into partidos (id, provincia, name) values (330, 10, 'limay mahuida');
insert into partidos (id, provincia, name) values (331, 11, 'castro barros');
insert into partidos (id, provincia, name) values (332, 11, 'general san martin');
insert into partidos (id, provincia, name) values (333, 11, 'general lavalle');
insert into partidos (id, provincia, name) values (334, 11, 'arauco');
insert into partidos (id, provincia, name) values (335, 11, 'gral.angel v.peñaloza');
insert into partidos (id, provincia, name) values (336, 11, 'san blas de los sauces');
insert into partidos (id, provincia, name) values (337, 11, 'independencia');
insert into partidos (id, provincia, name) values (338, 11, 'general ocampo');
insert into partidos (id, provincia, name) values (339, 11, 'chilecito');
insert into partidos (id, provincia, name) values (340, 11, 'famatina');
insert into partidos (id, provincia, name) values (341, 11, 'grl.juan facundo quiroga');
insert into partidos (id, provincia, name) values (342, 11, 'grl.angel v. peñaloza');
insert into partidos (id, provincia, name) values (343, 11, 'general belgrano');
insert into partidos (id, provincia, name) values (344, 11, 'general sarmiento');
insert into partidos (id, provincia, name) values (345, 11, 'capital');
insert into partidos (id, provincia, name) values (346, 11, 'gdor. gordillo');
insert into partidos (id, provincia, name) values (347, 11, 'general angel vicente peñaloza');
insert into partidos (id, provincia, name) values (348, 11, 'gobernador gordillo');
insert into partidos (id, provincia, name) values (349, 11, 'rosario vera peñaloza');
insert into partidos (id, provincia, name) values (350, 11, 'grl.san martin');
insert into partidos (id, provincia, name) values (351, 11, 'general la madrid');
insert into partidos (id, provincia, name) values (352, 11, 'general juan facundo quiroga');
insert into partidos (id, provincia, name) values (353, 11, 'generalocampo');
insert into partidos (id, provincia, name) values (354, 11, 'sanagasta');
insert into partidos (id, provincia, name) values (355, 12, 'san rafael');
insert into partidos (id, provincia, name) values (356, 12, 'lujan');
insert into partidos (id, provincia, name) values (357, 12, 'malargue');
insert into partidos (id, provincia, name) values (358, 12, 'guaymallen');
insert into partidos (id, provincia, name) values (359, 12, 'lavalle');
insert into partidos (id, provincia, name) values (360, 12, 'junin');
insert into partidos (id, provincia, name) values (361, 12, 'tupungato');
insert into partidos (id, provincia, name) values (362, 12, 'rivadavia');
insert into partidos (id, provincia, name) values (363, 12, 'maipu');
insert into partidos (id, provincia, name) values (364, 12, 'godoy cruz');
insert into partidos (id, provincia, name) values (365, 12, 'general alvear');
insert into partidos (id, provincia, name) values (366, 12, 'la paz');
insert into partidos (id, provincia, name) values (367, 12, 'tunuyan');
insert into partidos (id, provincia, name) values (368, 12, 'san carlos');
insert into partidos (id, provincia, name) values (369, 12, 'las heras');
insert into partidos (id, provincia, name) values (370, 12, 'lujan de cuyo');
insert into partidos (id, provincia, name) values (371, 12, 'san martin');
insert into partidos (id, provincia, name) values (372, 12, 'santa rosa');
insert into partidos (id, provincia, name) values (373, 12, 'capital');
insert into partidos (id, provincia, name) values (374, 13, '25 de mayo');
insert into partidos (id, provincia, name) values (375, 13, 'iguazu');
insert into partidos (id, provincia, name) values (376, 13, 'el dorado');
insert into partidos (id, provincia, name) values (377, 13, 'leandro n. alem');
insert into partidos (id, provincia, name) values (378, 13, 'apostoles');
insert into partidos (id, provincia, name) values (379, 13, 'cainguas');
insert into partidos (id, provincia, name) values (380, 13, 'leandro n.alem');
insert into partidos (id, provincia, name) values (381, 13, 'concepcion');
insert into partidos (id, provincia, name) values (382, 13, 'san pedro');
insert into partidos (id, provincia, name) values (383, 13, 'candelaria');
insert into partidos (id, provincia, name) values (384, 13, 'grl.manuel belgrano');
insert into partidos (id, provincia, name) values (385, 13, 'obera');
insert into partidos (id, provincia, name) values (386, 13, 'libertador grl.san martin');
insert into partidos (id, provincia, name) values (387, 13, 'san ignacio');
insert into partidos (id, provincia, name) values (388, 13, 'montecarlo');
insert into partidos (id, provincia, name) values (389, 13, 'general manuel belgrano');
insert into partidos (id, provincia, name) values (390, 13, 'lebertador grl.san martin');
insert into partidos (id, provincia, name) values (391, 13, 'el guarani');
insert into partidos (id, provincia, name) values (392, 13, 'eldorado');
insert into partidos (id, provincia, name) values (393, 13, 'capital');
insert into partidos (id, provincia, name) values (394, 13, 'guarani');
insert into partidos (id, provincia, name) values (395, 13, 'san javier');
insert into partidos (id, provincia, name) values (396, 13, 'libertador grl. san martin');
insert into partidos (id, provincia, name) values (397, 14, 'collon cura');
insert into partidos (id, provincia, name) values (398, 14, 'alumine');
insert into partidos (id, provincia, name) values (399, 14, 'minas');
insert into partidos (id, provincia, name) values (400, 14, 'añelo');
insert into partidos (id, provincia, name) values (401, 14, 'confluencia');
insert into partidos (id, provincia, name) values (402, 14, 'chos malal');
insert into partidos (id, provincia, name) values (403, 14, 'picunches');
insert into partidos (id, provincia, name) values (404, 14, 'norquin');
insert into partidos (id, provincia, name) values (405, 14, 'pehuenches');
insert into partidos (id, provincia, name) values (406, 14, 'loncopue');
insert into partidos (id, provincia, name) values (407, 14, 'huiliches');
insert into partidos (id, provincia, name) values (408, 14, 'zapala');
insert into partidos (id, provincia, name) values (409, 14, 'catan lil');
insert into partidos (id, provincia, name) values (410, 14, 'ñorquin');
insert into partidos (id, provincia, name) values (411, 14, 'los lagos');
insert into partidos (id, provincia, name) values (412, 14, 'picun leufu');
insert into partidos (id, provincia, name) values (413, 14, 'lacar');
insert into partidos (id, provincia, name) values (414, 14, 'ñoequin');
insert into partidos (id, provincia, name) values (415, 15, 'valcheta');
insert into partidos (id, provincia, name) values (416, 15, '25 de mayo');
insert into partidos (id, provincia, name) values (417, 15, 'el cuy');
insert into partidos (id, provincia, name) values (418, 15, 'ñorquinco');
insert into partidos (id, provincia, name) values (419, 15, 'general roca');
insert into partidos (id, provincia, name) values (420, 15, 'avellaneda');
insert into partidos (id, provincia, name) values (421, 15, 'conesa');
insert into partidos (id, provincia, name) values (422, 15, 'pichi mahuida');
insert into partidos (id, provincia, name) values (423, 15, 'san antonio');
insert into partidos (id, provincia, name) values (424, 15, 'pilcaniyeu');
insert into partidos (id, provincia, name) values (425, 15, '9 de julio');
insert into partidos (id, provincia, name) values (426, 15, 'adolfo alsina');
insert into partidos (id, provincia, name) values (427, 15, 'bariloche');
insert into partidos (id, provincia, name) values (428, 15, 'pihi mahuida');
insert into partidos (id, provincia, name) values (429, 16, 'la viña');
insert into partidos (id, provincia, name) values (430, 16, 'san martin');
insert into partidos (id, provincia, name) values (431, 16, 'oran');
insert into partidos (id, provincia, name) values (432, 16, 'anta');
insert into partidos (id, provincia, name) values (433, 16, 'gral.jose de san martin');
insert into partidos (id, provincia, name) values (434, 16, 'guachipas');
insert into partidos (id, provincia, name) values (435, 16, 'rosario de la frontera');
insert into partidos (id, provincia, name) values (436, 16, 'rivadavia');
insert into partidos (id, provincia, name) values (437, 16, 'metan');
insert into partidos (id, provincia, name) values (438, 16, 'san carlos');
insert into partidos (id, provincia, name) values (439, 16, 'grl.guemes');
insert into partidos (id, provincia, name) values (440, 16, 'cachi');
insert into partidos (id, provincia, name) values (441, 16, 'rosario de lerma');
insert into partidos (id, provincia, name) values (442, 16, 'cafayate');
insert into partidos (id, provincia, name) values (443, 16, 'los andes');
insert into partidos (id, provincia, name) values (444, 16, 'grl.jose de san martin');
insert into partidos (id, provincia, name) values (445, 16, 'capital');
insert into partidos (id, provincia, name) values (446, 16, 'grl.san martin');
insert into partidos (id, provincia, name) values (447, 16, 'general guemes');
insert into partidos (id, provincia, name) values (448, 16, 'cerrillos');
insert into partidos (id, provincia, name) values (449, 16, 'chicoana');
insert into partidos (id, provincia, name) values (450, 16, 'la poma');
insert into partidos (id, provincia, name) values (451, 16, 'la capital');
insert into partidos (id, provincia, name) values (452, 16, 'candelaria');
insert into partidos (id, provincia, name) values (453, 16, 'rosario');
insert into partidos (id, provincia, name) values (454, 16, 'iruya');
insert into partidos (id, provincia, name) values (455, 16, 'la caldera');
insert into partidos (id, provincia, name) values (456, 16, 'loa andes');
insert into partidos (id, provincia, name) values (457, 16, 'molinos');
insert into partidos (id, provincia, name) values (458, 16, 'santa victoria');
insert into partidos (id, provincia, name) values (459, 17, '9 de julio');
insert into partidos (id, provincia, name) values (460, 17, 'jachal');
insert into partidos (id, provincia, name) values (461, 17, 'albardon');
insert into partidos (id, provincia, name) values (462, 17, '25 de mayo');
insert into partidos (id, provincia, name) values (463, 17, 'santa lucia');
insert into partidos (id, provincia, name) values (464, 17, 'angaco');
insert into partidos (id, provincia, name) values (465, 17, 'iglesia');
insert into partidos (id, provincia, name) values (466, 17, 'valle fertil');
insert into partidos (id, provincia, name) values (467, 17, 'calingasta');
insert into partidos (id, provincia, name) values (468, 17, 'rivadavia');
insert into partidos (id, provincia, name) values (469, 17, 'caucete');
insert into partidos (id, provincia, name) values (470, 17, 'sarmiento');
insert into partidos (id, provincia, name) values (471, 17, 'pocito');
insert into partidos (id, provincia, name) values (472, 17, 'san martin');
insert into partidos (id, provincia, name) values (473, 17, 'chimbas');
insert into partidos (id, provincia, name) values (474, 17, 'iglesias');
insert into partidos (id, provincia, name) values (475, 17, 'ullun');
insert into partidos (id, provincia, name) values (476, 17, 'rawson');
insert into partidos (id, provincia, name) values (477, 17, 'capital');
insert into partidos (id, provincia, name) values (478, 17, 'zonda');
insert into partidos (id, provincia, name) values (479, 18, 'belgrano');
insert into partidos (id, provincia, name) values (480, 18, 'chacabuco');
insert into partidos (id, provincia, name) values (481, 18, 'la capital');
insert into partidos (id, provincia, name) values (482, 18, 'gobernador dupuy');
insert into partidos (id, provincia, name) values (483, 18, 'grl.pedernera');
insert into partidos (id, provincia, name) values (484, 18, 'ayacucho');
insert into partidos (id, provincia, name) values (485, 18, 'junin');
insert into partidos (id, provincia, name) values (486, 18, 'gonernador dupuy');
insert into partidos (id, provincia, name) values (487, 18, 'coronel pringles');
insert into partidos (id, provincia, name) values (488, 18, 'general pedernera');
insert into partidos (id, provincia, name) values (489, 18, 'gobernador duval');
insert into partidos (id, provincia, name) values (490, 18, 'iglesia');
insert into partidos (id, provincia, name) values (491, 18, 'libertador grl. san martin');
insert into partidos (id, provincia, name) values (492, 18, 'libertador grl.san martin');
insert into partidos (id, provincia, name) values (493, 18, 'libertador gr.san martin');
insert into partidos (id, provincia, name) values (494, 18, 'caucete');
insert into partidos (id, provincia, name) values (495, 19, 'guer aike');
insert into partidos (id, provincia, name) values (496, 19, 'deseado');
insert into partidos (id, provincia, name) values (497, 19, 'rio chico');
insert into partidos (id, provincia, name) values (498, 19, 'magallanes');
insert into partidos (id, provincia, name) values (499, 19, 'lago argentino');
insert into partidos (id, provincia, name) values (500, 19, 'corpen aike');
insert into partidos (id, provincia, name) values (501, 19, 'lago buenos aires');
insert into partidos (id, provincia, name) values (502, 20, 'general lopez');
insert into partidos (id, provincia, name) values (503, 20, 'rosario');
insert into partidos (id, provincia, name) values (504, 20, 'general obligado');
insert into partidos (id, provincia, name) values (505, 20, 'constitucion');
insert into partidos (id, provincia, name) values (506, 20, 'san lorenzo');
insert into partidos (id, provincia, name) values (507, 20, 'san javier');
insert into partidos (id, provincia, name) values (508, 20, 'la capital');
insert into partidos (id, provincia, name) values (509, 20, 'san cristobal');
insert into partidos (id, provincia, name) values (510, 20, 'iriondo');
insert into partidos (id, provincia, name) values (511, 20, 'castellanos');
insert into partidos (id, provincia, name) values (512, 20, 'nueve de julio');
insert into partidos (id, provincia, name) values (513, 20, 'caseros');
insert into partidos (id, provincia, name) values (514, 20, 'san jeronimo');
insert into partidos (id, provincia, name) values (515, 20, 'belgrano');
insert into partidos (id, provincia, name) values (516, 20, 'capital');
insert into partidos (id, provincia, name) values (517, 20, 'san justo');
insert into partidos (id, provincia, name) values (518, 20, 'grl.obligado');
insert into partidos (id, provincia, name) values (519, 20, 'la caputal');
insert into partidos (id, provincia, name) values (520, 20, 'grl.lopez');
insert into partidos (id, provincia, name) values (521, 20, 'vera');
insert into partidos (id, provincia, name) values (522, 20, '9 de julio');
insert into partidos (id, provincia, name) values (523, 20, 'san martin');
insert into partidos (id, provincia, name) values (524, 20, 'las colonias');
insert into partidos (id, provincia, name) values (525, 20, 'garay');
insert into partidos (id, provincia, name) values (526, 20, 'castelanos');
insert into partidos (id, provincia, name) values (527, 20, 'las colinas');
insert into partidos (id, provincia, name) values (528, 21, 'banda');
insert into partidos (id, provincia, name) values (529, 21, 'moreno');
insert into partidos (id, provincia, name) values (530, 21, 'alberdi');
insert into partidos (id, provincia, name) values (531, 21, 'pellegrini');
insert into partidos (id, provincia, name) values (532, 21, 'ojo de agua');
insert into partidos (id, provincia, name) values (533, 21, 'rio hondo');
insert into partidos (id, provincia, name) values (534, 21, 'general taboada');
insert into partidos (id, provincia, name) values (535, 21, 'choya');
insert into partidos (id, provincia, name) values (536, 21, 'capital');
insert into partidos (id, provincia, name) values (537, 21, 'aguirre');
insert into partidos (id, provincia, name) values (538, 21, 'silipica');
insert into partidos (id, provincia, name) values (539, 21, 'belgrano');
insert into partidos (id, provincia, name) values (540, 21, 'figueroa');
insert into partidos (id, provincia, name) values (541, 21, 'salavina');
insert into partidos (id, provincia, name) values (542, 21, 'quebrachos');
insert into partidos (id, provincia, name) values (543, 21, 'robles');
insert into partidos (id, provincia, name) values (544, 21, 'avellaneda');
insert into partidos (id, provincia, name) values (545, 21, 'jimenez');
insert into partidos (id, provincia, name) values (546, 21, 'atamisqui');
insert into partidos (id, provincia, name) values (547, 21, 'san martin');
insert into partidos (id, provincia, name) values (548, 21, 'matara');
insert into partidos (id, provincia, name) values (549, 21, 'salayina');
insert into partidos (id, provincia, name) values (550, 21, 'guasayan');
insert into partidos (id, provincia, name) values (551, 21, 'copo');
insert into partidos (id, provincia, name) values (552, 21, 'brigadier juan felipe ibarra');
insert into partidos (id, provincia, name) values (553, 21, 'dobles');
insert into partidos (id, provincia, name) values (554, 21, 'sarmiento');
insert into partidos (id, provincia, name) values (555, 21, 'loreto');
insert into partidos (id, provincia, name) values (556, 21, 'mitre');
insert into partidos (id, provincia, name) values (557, 21, 'rivadavia');
insert into partidos (id, provincia, name) values (558, 22, 'ushuaia');
insert into partidos (id, provincia, name) values (559, 22, 'islas del atlantico sur');
insert into partidos (id, provincia, name) values (560, 22, 'sector antartico argentino');
insert into partidos (id, provincia, name) values (561, 22, 'rio grande');
insert into partidos (id, provincia, name) values (562, 22, 'is.del atlantico sur e is.malvinas');
insert into partidos (id, provincia, name) values (563, 22, 'antartida argentina');
insert into partidos (id, provincia, name) values (564, 23, 'burruyacu');
insert into partidos (id, provincia, name) values (565, 23, 'trancas');
insert into partidos (id, provincia, name) values (566, 23, 'monteros');
insert into partidos (id, provincia, name) values (567, 23, 'leales');
insert into partidos (id, provincia, name) values (568, 23, 'cruz alta');
insert into partidos (id, provincia, name) values (569, 23, 'rio chico');
insert into partidos (id, provincia, name) values (570, 23, 'chicligasta');
insert into partidos (id, provincia, name) values (571, 23, 'tafi');
insert into partidos (id, provincia, name) values (572, 23, 'graneros');
insert into partidos (id, provincia, name) values (573, 23, 'famailla');
insert into partidos (id, provincia, name) values (574, 23, 'capital');
