INSERT INTO provincias (id, nombre, pais_id) VALUES (1, 'BUENOS AIRES',1);
INSERT INTO provincias (id, nombre, pais_id) VALUES (2, 'CATAMARCA',1);
INSERT INTO provincias (id, nombre, pais_id) VALUES (3, 'CHACO',1);
INSERT INTO provincias (id, nombre, pais_id) VALUES (4, 'CHUBUT',1);
INSERT INTO provincias (id, nombre, pais_id) VALUES (5, 'CORDOBA',1);
INSERT INTO provincias (id, nombre, pais_id) VALUES (6, 'CORRIENTES',1);
INSERT INTO provincias (id, nombre, pais_id) VALUES (7, 'ENTRE RIOS',1);
INSERT INTO provincias (id, nombre, pais_id) VALUES (8, 'FORMOSA',1);
INSERT INTO provincias (id, nombre, pais_id) VALUES (9, 'JUJUY',1);
INSERT INTO provincias (id, nombre, pais_id) VALUES (10, 'LA PAMPA',1);
INSERT INTO provincias (id, nombre, pais_id) VALUES (11, 'LA RIOJA',1);
INSERT INTO provincias (id, nombre, pais_id) VALUES (12, 'MENDOZA',1);
INSERT INTO provincias (id, nombre, pais_id) VALUES (13, 'MISIONES',1);
INSERT INTO provincias (id, nombre, pais_id) VALUES (14, 'NEUQUEN',1);
INSERT INTO provincias (id, nombre, pais_id) VALUES (15, 'RIO NEGRO',1);
INSERT INTO provincias (id, nombre, pais_id) VALUES (16, 'SALTA',1);
INSERT INTO provincias (id, nombre, pais_id) VALUES (17, 'SAN JUAN',1);
INSERT INTO provincias (id, nombre, pais_id) VALUES (18, 'SAN LUIS',1);
INSERT INTO provincias (id, nombre, pais_id) VALUES (19, 'SANTA CRUZ',1);
INSERT INTO provincias (id, nombre, pais_id) VALUES (20, 'SANTA FE',1);
INSERT INTO provincias (id, nombre, pais_id) VALUES (21, 'SANTIAGO DEL ESTERO',1);
INSERT INTO provincias (id, nombre, pais_id) VALUES (22, 'TIERRA DEL FUEGO',1);
INSERT INTO provincias (id, nombre, pais_id) VALUES (23, 'TUCUMAN',1);
